---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sanctum-compute
  namespace: sanctum
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    count/deployments.apps: "20"
    services.loadbalancers: "0"
