---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nimbus

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: nimbus-orders-api-dev
      environment: dev
    includeSelectors: false

images:
  - name: nimbus/orders-api
    newName: 123456789012.dkr.ecr.eu-central-1.amazonaws.com/nimbus/orders-api
    newTag: dev-a1b2c3d

replicas:
  - name: nimbus-orders-api
    count: 2

patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
  - path: patch-hpa.yaml
