---
apiVersion: v1
kind: Service
metadata:
  name: nimbus-orders-api
  namespace: nimbus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nimbus-orders-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
