---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nimbus

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: nimbus-orders-api-prod
      environment: prod
    includeSelectors: false

images:
  - name: nimbus/orders-api
    newName: 123456789012.dkr.ecr.eu-central-1.amazonaws.com/nimbus/orders-api
    newTag: 1.8.0

replicas:
  - name: nimbus-orders-api
    count: 4

patches:
  - path: patch-deployment.yaml
  - path: patch-configmap.yaml
  - path: patch-hpa.yaml
  - target:
      kind: Deployment
      name: nimbus-orders-api
    patch: |-
      - op: replace
        path: /spec/template/spec/topologySpreadConstraints/0/whenUnsatisfiable
        value: DoNotSchedule
